resolver: nightly-2017-09-06

flags: {}

packages:
  - '.'
  - location:
      git: git://github.com/haskoin/haskoin
      commit: 3279f5c83026fe25e8761213de7e0cdcc6e2bd0e
    extra-dep: true
    subdirs:
      - haskoin-core
  - location:
      git: git://github.com/WraithM/network-bitcoin
      commit: f58f7ad68d8ae6601a80cff00e1937b9065184ab
    extra-dep: true

extra-deps:
  - murmur3-1.0.3
  - pbkdf-1.1.1.1
  - secp256k1-0.5.2
  - largeword-1.2.5
  - either-4.5
