resolver: nightly-2017-09-06

flags: {}

packages:
  - '.'
  - location:
      git: git://github.com/bitnomial/haskoin
      commit: 509ad423e4734498e96d94fdece36ee5f0e00a05
    extra-dep: true
    subdirs:
      - haskoin-core
  - location:
      git: git://github.com/WraithM/network-bitcoin
      commit: f623f3821e9c422e9e7fb0bff6a69435c9b37a25
    extra-dep: true

extra-deps:
  - murmur3-1.0.3
  - pbkdf-1.1.1.1
  - secp256k1-0.4.2
  - largeword-1.2.5
