resolver: nightly-2015-12-28 # lts-3.20

flags: {}

packages:
  - '.'
  - haskoin/haskoin-core
  - network-bitcoin

extra-deps:
  - murmur3-1.0.0
  - pbkdf-1.1.1.1
  - secp256k1-0.4.2
  - largeword-1.2.4
